---
abstract: 'prepend lines at the top of your perl files'
author:
  - 'Jerome Quelin'
build_requires:
  Dist::Zilla::Tester: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Path::Class: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
generated_by: 'Dist::Zilla version 2.100880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Prepender
provides:
  Dist::Zilla::Plugin::Prepender:
    file: lib/Dist/Zilla/Plugin/Prepender.pm
    version: 1.100960
requires:
  Dist::Zilla::Role::FileMunger: 0
  Moose: 0
  MooseX::Has::Sugar: 0
  perl: 5.008
resources:
  MailingList: http://www.listbox.com/subscribe/?list_id=139292
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-Prepender/
  repository: http://github.com/jquelin/dist-zilla-plugin-prepender.git
version: 1.100960
